"use client";
import type { Metadata } from "next";
import { Delius } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/PageHeader";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const delius = Delius({ subsets: ["latin"], weight: "400" });
// export const metadata: Metadata = {
//   title: "Gwiflora's Echo",
//   description: "Personal Blog Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      <body className={delius.className}>
        <div className="main-background bg-mint-100 mx-auto min-h-screen p-20">
          <PageHeader />
          <AntdRegistry>{children}</AntdRegistry>
        </div>
      </body>
    </html>
  );
}
