name: Next.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn 4)
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate
          yarn -v

      - name: Cache Yarn Berry artifacts
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Inject commit id (app only)
        run: |
          echo "NEXT_PUBLIC_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install deps
        run: yarn install --immutable

      - name: Build
        env:
          NEXT_PUBLIC_COMMIT_ID: ${{ env.NEXT_PUBLIC_COMMIT_ID }}
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_DEPLOYMENT_URL: ${{ secrets.NEXT_PUBLIC_DEPLOYMENT_URL }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: yarn build
