name: Next.js CI

on:
  push:
    branches: [main, dev]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build (with submodules)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          token:${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node (v20) + Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: corepack enable

      - name: Inject commit ids (app & content)
        run: |
          echo "NEXT_PUBLIC_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          CONTENT_SHA=$(git rev-parse --short HEAD:src/app/content 2>/dev/null || git -C src/app/content rev-parse --short HEAD || echo unknown)
          echo "NEXT_PUBLIC_SUBMODULE_COMMIT_ID=${CONTENT_SHA}" >> $GITHUB_ENV

      - name: Install deps (Yarn 4 immutable)
        run: yarn install --immutable

      - name: Build
        env:
          NEXT_PUBLIC_COMMIT_ID: ${{ env.NEXT_PUBLIC_COMMIT_ID }}
          NEXT_PUBLIC_SUBMODULE_COMMIT_ID: ${{ env.NEXT_PUBLIC_SUBMODULE_COMMIT_ID }}
          NEXT_TELEMETRY_DISABLED: 1
        run: yarn build

      - name: Upload build artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
